// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "bs-platform/lib/es6/caml_array.js";

var theText = {
  contents: ""
};

var textArea = document.getElementById("textEditor");

var previewArea = document.getElementById("textView");

var smallCheck = document.getElementById("selectSmall");

var largeCheck = document.getElementById("selectLarge");

var regularCheck = document.getElementById("selectRegular");

function sizeSelection(text) {
  var smallChecked = smallCheck.checked;
  var regularChecked = regularCheck.checked;
  if (smallChecked) {
    return {
            TAG: /* Small */0,
            _0: text
          };
  } else if (regularChecked) {
    return {
            TAG: /* Regular */1,
            _0: text
          };
  } else {
    return {
            TAG: /* Large */2,
            _0: text
          };
  }
}

function removeSizeClass(param) {
  var classList = previewArea.classList;
  if (classList.length > 2) {
    return classList.remove(Caml_array.get(classList, 2));
  }
  
}

function addSizeClass(className) {
  return previewArea.classList.add(className);
}

function updateClass(className) {
  removeSizeClass(undefined);
  return addSizeClass(className);
}

function handleUpdateClass(text) {
  switch (text.TAG | 0) {
    case /* Small */0 :
        removeSizeClass(undefined);
        addSizeClass("text-sm");
        return text._0;
    case /* Regular */1 :
        removeSizeClass(undefined);
        addSizeClass("text-2xl");
        return text._0;
    case /* Large */2 :
        removeSizeClass(undefined);
        addSizeClass("text-6xl");
        return text._0;
    
  }
}

function updatePreviewText(text) {
  previewArea.innerText = handleUpdateClass(text);
  
}

function handleTextAreaUpdate(param) {
  theText.contents = textArea.value;
  return updatePreviewText(sizeSelection(theText.contents));
}

textArea.addEventListener("keyup", handleTextAreaUpdate);

smallCheck.addEventListener("click", handleTextAreaUpdate);

largeCheck.addEventListener("click", handleTextAreaUpdate);

regularCheck.addEventListener("click", handleTextAreaUpdate);

export {
  theText ,
  textArea ,
  previewArea ,
  smallCheck ,
  largeCheck ,
  regularCheck ,
  sizeSelection ,
  removeSizeClass ,
  addSizeClass ,
  updateClass ,
  handleUpdateClass ,
  updatePreviewText ,
  handleTextAreaUpdate ,
  
}
/* textArea Not a pure module */
