// Generated by ReScript, PLEASE EDIT WITH CARE


var textArea = document.getElementById("textEditor");

var previewArea = document.getElementById("textView");

function handleTextAreaUpdate(param) {
  previewArea.innerText = textArea.value;
  
}

textArea.addEventListener("keyup", handleTextAreaUpdate);

export {
  textArea ,
  previewArea ,
  handleTextAreaUpdate ,
  
}
/* textArea Not a pure module */
