// Generated by ReScript, PLEASE EDIT WITH CARE


var textArea = document.getElementById("textEditor");

function handleTextAreaUpdate(param) {
  console.log(textArea.value);
  
}

textArea.addEventListener("keyup", handleTextAreaUpdate);

export {
  textArea ,
  handleTextAreaUpdate ,
  
}
/* textArea Not a pure module */
